name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="environment=${{ secrets.ENVIRONMENT }}" \
            -var="mongodb_project_name=${{ secrets.MONGODB_PROJECT_NAME }}" \
            -var="mongodb_cluster_name=${{ secrets.MONGODB_CLUSTER_NAME }}" \
            -var="mongodb_username=${{ secrets.MONGODB_USERNAME }}" \
            -var="mongodb_password=${{ secrets.MONGODB_PASSWORD }}" \
            -var="mongodb_database_name=${{ secrets.MONGODB_DATABASE_NAME }}" \
            -var="react_app_bucket_name=${{ secrets.REACT_APP_BUCKET_NAME }}" \
            -var="flutter_app_bucket_name=${{ secrets.FLUTTER_APP_BUCKET_NAME }}" \
            -var="api_gateway_name=${{ secrets.API_GATEWAY_NAME }}" \
            -var="mongodb_atlas_org_id=${{ secrets.MONGODB_ATLAS_ORG_ID }}" \
            -var="mongodb_atlas_public_key=${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}" \
            -var="mongodb_atlas_private_key=${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}" \
            -var="grafana_cloud_api_key=${{ secrets.GRAFANA_CLOUD_API_KEY }}" \
            -var="ec2_key_name=${{ secrets.EC2_KEY_NAME }}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          terraform apply -auto-approve \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="environment=${{ secrets.ENVIRONMENT }}" \
            -var="mongodb_project_name=${{ secrets.MONGODB_PROJECT_NAME }}" \
            -var="mongodb_cluster_name=${{ secrets.MONGODB_CLUSTER_NAME }}" \
            -var="mongodb_username=${{ secrets.MONGODB_USERNAME }}" \
            -var="mongodb_password=${{ secrets.MONGODB_PASSWORD }}" \
            -var="mongodb_database_name=${{ secrets.MONGODB_DATABASE_NAME }}" \
            -var="react_app_bucket_name=${{ secrets.REACT_APP_BUCKET_NAME }}" \
            -var="flutter_app_bucket_name=${{ secrets.FLUTTER_APP_BUCKET_NAME }}" \
            -var="api_gateway_name=${{ secrets.API_GATEWAY_NAME }}" \
            -var="mongodb_atlas_org_id=${{ secrets.MONGODB_ATLAS_ORG_ID }}" \
            -var="mongodb_atlas_public_key=${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}" \
            -var="mongodb_atlas_private_key=${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}" \
            -var="grafana_cloud_api_key=${{ secrets.GRAFANA_CLOUD_API_KEY }}" \
            -var="ec2_key_name=${{ secrets.EC2_KEY_NAME }}"
